[build]
  command = "echo 'No build command needed for static site'"
  publish = "public"

[dev]
  command = "node server.js"
  port = 3000
  targetPort = 3000

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
